[workspace]
resolver = "2"
members = [
    "crates/patch-perl",
    "crates/patch-perl-plugin",
    "crates/patch-perl-plugin-example",
]

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "Artistic-1.0 OR GPL-1.0-or-later"
repository = "https://github.com/uperl/patch-perl"
authors = ["Graham Ollis <plicease@cpan.org>"]

[workspace.dependencies]
patch-perl = { path = "crates/patch-perl", version = "0.1.1" }
patch-perl-plugin = { path = "crates/patch-perl-plugin", version = "0.1.1" }
regex = "1.10"
libloading = "0.8"
thiserror = "2.0"
log = "0.4"
tempfile = "3.10"
